name: github pages

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment

jobs:
  deploy:
    name: Deploy doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Use OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: '5.2'
          dune-cache: true
          allow-prerelease-opam: true

      # Until there's a new release of `trace`, we need to pin it.
      - run: opam pin https://github.com/c-cube/ocaml-trace.git#HEAD -y -n
      - run: opam pin . -y -n
      - run: opam install odig imandrakit imandrakit-thread imandrakit-io imandrakit-log
      - run: opam exec -- odig odoc --cache-dir=_doc/ imandrakit imandrakit-thread imandrakit-io imandrakit-log

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_doc/html
          destination_dir: .
          enable_jekyll: false
