name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-all-versions:
    name: build
    timeout-minutes: 15
    strategy:
      fail-fast: true
      matrix:
        os:
            - ubuntu-latest
              #- macos-latest
              #- windows-latest
        ocaml-compiler:
            - '4.14'
            - '5.2'

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
          allow-prerelease-opam: true

      - run: opam install -t imandrakit imandrakit-log imandrakit-io --deps-only
      - run: opam exec -- dune build @install -p imandrakit,imandrakit-log,imandrakit-io
      - run: opam exec -- dune build @runtest -p imandrakit,imandrakit-log,imandrakit-io

      # install some depopts and build+test again
      - run: opam install camlzip
      - run: opam exec -- dune build @install @runtest -p imandrakit,imandrakit-log,imandrakit-io

  build-ocaml5:
    name: build-ocaml5
    timeout-minutes: 15
    strategy:
      fail-fast: true
      matrix:
        os:
            - ubuntu-latest
              #- macos-latest
              #- windows-latest
        ocaml-compiler:
            - '5.1'
            - '5.2'

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
          allow-prerelease-opam: true

      - run: opam install -t imandrakit imandrakit-log imandrakit-io imandrakit-thread --deps-only
      - run: opam exec -- dune build @install -p imandrakit,imandrakit-io,imandrakit-log,imandrakit-thread
      - run: opam exec -- dune build @runtest -p imandrakit,imandrakit-io,imandrakit-log,imandrakit-thread

  format:
    name: format
    strategy:
      matrix:
        ocaml-compiler:
            - '5.1'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@main
      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
          allow-prerelease-opam: true

      - run: opam install ocamlformat.0.26.2
      - run: opam exec -- make format-check

# vim:foldmethod=indent
